### ISSUE TITLE
Review of your Developer Guide

### ISSUE THREAD

**Issue by kewenlok** [AY2122S1-CS2113-T16-1/tp#117]
1. Is it better to have a content page for your developer guide to help readers navigate your content easily?

2. Would it be better if you include instructions for setting up and getting started your application as shown in the example below so that other developers can get started quickly with your application?

<img width="753" alt="Screenshot 2021-10-30 at 5 01 26 PM" src="https://user-images.githubusercontent.com/70790702/139526872-67316d1f-cc6a-40f6-a332-6411e9340a65.png">

3. Do not forget to replace the placeholders similar to the one below before submitting.

<img width="785" alt="Screenshot 2021-10-30 at 4 52 07 PM" src="https://user-images.githubusercontent.com/70790702/139526623-e6a1ebdc-cee3-4bb3-9979-ed6736f90696.png">

4. This class diagram is good, however, unreadable when you print it out in PDF for submission. So consider splitting the diagram into multiple smaller diagrams. It is also to avoid overlapping notations.

<img width="848" alt="Screenshot 2021-10-30 at 4 55 15 PM" src="https://user-images.githubusercontent.com/70790702/139526723-7f83a285-8303-4d26-9dbb-d39c8ee0390f.png">

5. Architecture diagram is different from the other diagrams such as the sequence diagram shown below. It is used to show the overall relationship between all components in your application with a simplified view. For an example of the architecture diagram, you may refer to the address book 3 developer guide here: https://se-education.org/addressbook-level3/DeveloperGuide.html#architecture.

<img width="650" alt="Screenshot 2021-10-30 at 4 57 11 PM" src="https://user-images.githubusercontent.com/70790702/139526812-66247c41-5747-4ddb-99c1-bc7c0350db63.png">

6. Similarly, in the sequence diagram shown on the image above, the `TextUi` entity's self-invocation notation is incorrect as you will need a shorter overlapping activation bar for each self-invocation method. An example is shown below.

<img width="180" alt="Screenshot 2021-10-30 at 5 06 16 PM" src="https://user-images.githubusercontent.com/70790702/139527044-a165a9ae-4a17-40e3-92a0-b759c7e2651d.png">

7. Would it be better if the class diagram below if clearer?

<img width="472" alt="Screenshot 2021-10-30 at 5 09 31 PM" src="https://user-images.githubusercontent.com/70790702/139527152-858178ff-7653-4783-a2c1-53e41b07a2c9.png">

8. You will need to hide the footer of the `EditCommand` sequence diagram as it is not in the standard UML notation. The footer can be hidden by adding `hide footbox` in your puml file.

<img width="851" alt="Screenshot 2021-10-30 at 5 10 32 PM" src="https://user-images.githubusercontent.com/70790702/139527288-f0259ca6-7b61-4b3d-9a4e-8b5666a50faa.png">

9. Would it be easier for the user to read your sequence diagram below if you split the call to each editing command into different sequence diagrams?

<img width="858" alt="Screenshot 2021-10-30 at 5 16 10 PM" src="https://user-images.githubusercontent.com/70790702/139527391-e1c5e17b-6b8d-43b7-95dd-a61021863a39.png">

10. In general, good effort in writing a developer guide with the use of different diagrams. However, you may want to fill in more explanations and implementation details with the help of visual aids as deemed necessary by you for a developer to understand what your code does based on the guide itself.

**Comment by exetr** [comment]
- [ ] DG Content page
- [ ] Setting up
- [ ] Getting started
- [ ] Acknowledgements
- [ ] Make command class diagram smaller
- [ ] Do architecture diagram
- [ ] Fix TextUI self invocation activation bar
- [ ] Make Item class diagram clearer
- [ ] Hide footer of edit command sequence diagram
- [ ] Split edit command sequence diagram
- [ ] Add annotations and descriptions
